apiVersion: storage.k8s.io/v1
# Provisiona PV automaticamente, pode usar vários provisioners diferentes, ver documentação
kind: StorageClass
metadata:
    name: slow
provisioner: kubernetes.io/gce-pd
parameters:
    type: pd-standard
    fstype: ext4
    replication-type: none