apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    # Permite acesso externo por localhost:30000 que redireciona para porta 80 do pod
    # Todos nós do cluster compartilham a mesma porta
    - port: 80
      nodePort: 30000
  selector:
    app: portal-noticias