apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  # Tem integração com loadbalancer dos cloud providers
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30000
    selector:
      app: primeiro-pod